name: ✨ 功能建议
description: 建议新功能或改进现有功能
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您的功能建议！请填写以下信息帮助我们更好地理解您的需求。

  - type: textarea
    id: feature-description
    attributes:
      label: 功能描述
      description: 请详细描述您希望添加的功能
      placeholder: 清晰简洁地描述您想要的功能...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 其他信息
      description: 添加任何其他相关信息、截图或参考资料

  - type: checkboxes
    id: terms
    attributes:
      label: 确认事项
      description: 提交前请确认以下事项
      options:
        - label: 我已经搜索过现有的 issues，确认这不是重复建议
          required: true
        - label: 我已经阅读了文档和 README
          required: true
        - label: 这个功能符合项目的目标和范围
          required: true
        - label: 我愿意参与讨论并提供更多信息
          required: true