name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    env:
      PYTHONIOENCODING: utf-8
      PYTHONLEGACYWINDOWSSTDIO: utf-8
      PYTHONUTF8: 1
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pyyaml
        pip install openai
        pip install packaging
        pip install prompt-toolkit
        
    - name: Create log directory
      run: |
        mkdir log
        echo "Placeholder log file" > log/placeholder.log
        
    - name: Build EXE
      run: |
        python -X utf8 build_exe.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenAI_Chat_Tool_CLI
        path: dist/octool_cli.exe